# Generated by Django 3.2.9 on 2021-11-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['apellidos'],
            },
        ),
    ]
