# Generated by Django 3.2.9 on 2021-11-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rol'),
        ),
    ]
