# Generated by Django 4.0.4 on 2022-04-24 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='hash',
            field=models.CharField(blank=True, max_length=254, verbose_name='hash'),
        ),
        migrations.CreateModel(
            name='EnvioOffline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(blank=True, max_length=254, verbose_name='hash')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionarios')),
            ],
            options={
                'db_table': 'EnvioOffline',
            },
        ),
    ]
