# Generated by Django 4.0.4 on 2022-04-24 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enviooffline',
            table='Envio_offline',
        ),
    ]
