# Generated by Django 4.0.2 on 2022-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cuestionarios_npreguntas'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='titulo',
            field=models.CharField(blank=True, max_length=254, verbose_name='titulo'),
        ),
    ]
