# Generated by Django 4.0.4 on 2022-04-24 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_enviooffline_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enviooffline',
            unique_together={('idCuestionario', 'idAlumno')},
        ),
    ]
