# Generated by Django 4.0.4 on 2022-04-24 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notas_hash_enviooffline'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notas',
            unique_together={('idCuestionario', 'idAlumno')},
        ),
    ]
