# Generated by Django 4.0.2 on 2022-04-02 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_preguntas_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='titulo',
        ),
    ]
