# Generated by Django 4.0.2 on 2022-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_perteneceacuestionario_puntosfallo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perteneceacuestionario',
            name='puntosFallo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='puntosFallo'),
        ),
        migrations.AlterField(
            model_name='perteneceacuestionario',
            name='puntosAcierto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30, verbose_name='puntosAcierto'),
        ),
    ]
