# Generated by Django 3.2.4 on 2021-12-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211201_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=7, verbose_name='role'),
        ),
        migrations.AlterUniqueTogether(
            name='esalumno',
            unique_together={('idAlumno', 'idAsignatura')},
        ),
        migrations.AlterUniqueTogether(
            name='imparte',
            unique_together={('idProfesor', 'idAsignatura')},
        ),
    ]
