# Generated by Django 4.0.2 on 2022-02-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_perteneceacuestionario_puntosfallo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='secuencial',
            field=models.IntegerField(default=1, verbose_name='secuencial'),
        ),
    ]
