# Generated by Django 3.2.9 on 2021-11-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionario',
            name='nPreguntas',
            field=models.IntegerField(default=0, verbose_name='nPreguntas'),
        ),
        migrations.AlterField(
            model_name='perteneceacuestionario',
            name='puntosAcierto',
            field=models.IntegerField(default=0, verbose_name='puntos_acierto'),
        ),
        migrations.AlterField(
            model_name='perteneceacuestionario',
            name='puntosFallo',
            field=models.IntegerField(default=0, verbose_name='puntosFallo'),
        ),
    ]
