# Generated by Django 3.2.9 on 2021-11-04 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211104_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(blank=True, max_length=254, verbose_name='asignatura')),
            ],
            options={
                'ordering': ['asignatura'],
            },
        ),
        migrations.CreateModel(
            name='Cuestionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='titulo')),
                ('nPreguntas', models.IntegerField(default=0, verbose_name='nPreguntas')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignaturas')),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='OpcionesTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(blank=True, max_length=254, verbose_name='opcion')),
            ],
        ),
        migrations.RenameModel(
            old_name='Pregunta',
            new_name='Preguntas',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuarios',
        ),
        migrations.CreateModel(
            name='RespuestasTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(blank=True, max_length=254, verbose_name='respuesta')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
            ],
            options={
                'ordering': ['respuesta'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOpcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opcionestest')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasEnviadasText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Respuesta', models.CharField(blank=True, max_length=254, verbose_name='respuesta')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionarios')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
            ],
            options={
                'ordering': ['idPregunta'],
            },
        ),
        migrations.CreateModel(
            name='RespuestasEnviadasTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionarios')),
                ('idPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas')),
                ('idRespuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.opcionestest')),
            ],
            options={
                'ordering': ['idPregunta'],
            },
        ),
        migrations.AddField(
            model_name='opcionestest',
            name='idPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preguntas'),
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0, verbose_name='nota')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
                ('idCuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionarios')),
            ],
        ),
        migrations.CreateModel(
            name='Imparte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignaturas')),
                ('idProfesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EsAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
                ('idAsignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asignaturas')),
            ],
        ),
        migrations.AddField(
            model_name='cuestionarios',
            name='idProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios'),
        ),
        migrations.AlterField(
            model_name='perteneceacuestionario',
            name='idCuestionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuestionarios'),
        ),
        migrations.DeleteModel(
            name='Cuestionario',
        ),
    ]
