# Generated by Django 3.2.4 on 2021-11-12 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211104_1119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asignaturas',
            table='asignaturas',
        ),
        migrations.AlterModelTable(
            name='cuestionarios',
            table='cuestionarios',
        ),
        migrations.AlterModelTable(
            name='esalumno',
            table='es_alumno',
        ),
        migrations.AlterModelTable(
            name='imparte',
            table='imparte',
        ),
        migrations.AlterModelTable(
            name='notas',
            table='notas',
        ),
        migrations.AlterModelTable(
            name='opcionestest',
            table='opciones_test',
        ),
        migrations.AlterModelTable(
            name='perteneceacuestionario',
            table='pertenece_cuestionario',
        ),
        migrations.AlterModelTable(
            name='preguntas',
            table='preguntas',
        ),
        migrations.AlterModelTable(
            name='respuestasenviadastest',
            table='respuestas_enviadas_test',
        ),
        migrations.AlterModelTable(
            name='respuestasenviadastext',
            table='respuestas_enviadas_text',
        ),
        migrations.AlterModelTable(
            name='respuestastest',
            table='respuestas_test',
        ),
        migrations.AlterModelTable(
            name='respuestastexto',
            table='respuestas_texto',
        ),
        migrations.AlterModelTable(
            name='usuarios',
            table='usuarios',
        ),
    ]
