# Generated by Django 4.0.2 on 2022-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_cuestionarios_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='duracion',
            field=models.IntegerField(default=10, verbose_name='duracion'),
        ),
    ]
