# Generated by Django 4.0.2 on 2022-02-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cuestionarios_duracion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuestionarios',
            unique_together={('idAsignatura', 'titulo')},
        ),
    ]
