# Generated by Django 4.0.2 on 2022-02-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cuestionarios_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='preguntas',
            unique_together={('pregunta', 'tipoPregunta')},
        ),
    ]
