# Generated by Django 4.0.2 on 2022-02-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_preguntas_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcionestest',
            unique_together={('opcion', 'idPregunta')},
        ),
    ]
