# Generated by Django 4.0.2 on 2022-02-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_opcionestest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuestionarios',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='titulo'),
        ),
    ]
