# Generated by Django 4.0.2 on 2022-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_cuestionarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuestionarios',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='password'),
        ),
    ]
